services:
  postgres:
    image: postgres:16
    container_name: todo_postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    volumes:
      - todo_pg_data:/var/lib/postgresql/data
 
volumes:
  todo_pg_data: